# Generated by Django 4.2.13 on 2026-05-27 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('factor_kg_co2e_per_unit', models.DecimalField(decimal_places=6, max_digits=12)),
                ('unit', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', '-year'],
                'unique_together': {('category', 'year')},
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=10)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(choices=[('fuel', 'Fuel Combustion'), ('electricity', 'Purchased Electricity'), ('flight', 'Business Travel — Flight'), ('hotel', 'Business Travel — Hotel'), ('ground_transport', 'Business Travel — Ground Transport'), ('procurement', 'Procurement (goods/services)')], max_length=30)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('facility_code', models.CharField(blank=True, max_length=100)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('raw_quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('raw_unit', models.CharField(max_length=30)),
                ('normalized_quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('normalized_unit', models.CharField(max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('original_values', models.JSONField(blank=True, null=True)),
                ('was_edited', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged for Investigation')], default='PENDING', max_length=10)),
                ('flags', models.JSONField(default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.emissionfactor')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.organization')),
                ('raw_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized', to='ingestion.rawrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date', 'facility_code'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('BATCH_UPLOADED', 'Batch Uploaded'), ('BATCH_FAILED', 'Batch Failed'), ('RECORD_APPROVED', 'Record Approved'), ('RECORD_REJECTED', 'Record Rejected'), ('RECORD_FLAGGED', 'Record Flagged'), ('RECORD_EDITED', 'Record Edited'), ('RECORD_REOPENED', 'Record Reopened')], max_length=30)),
                ('before_state', models.JSONField(default=dict)),
                ('after_state', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='ingestion.importbatch')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.organization')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='emissions.normalizedrecord')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['org', 'status'], name='emissions_n_org_id_4d9ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['org', 'scope', 'activity_date'], name='emissions_n_org_id_ae1647_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['org', 'source_type', 'activity_date'], name='emissions_n_org_id_37f0eb_idx'),
        ),
    ]
